# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
use_frameworks!
target 'Jabali Espacial' do
	project 'Jabali Espacial.xcodeproj'
	pod 'Google-Mobile-Ads-SDK', '~> 8.13.0'
	pod 'GoogleUserMessagingPlatform', '~> 2.0.0'
end
